coef.SLRMss<-
  function(object,H0=FALSE){
  out=NULL
  if(H0==FALSE){
  out$beta=object$beta.coefficients[,1]
  out$phi=object$phi[,1]
  }else{
  out$beta=object$beta.coefficients.h0[,1]
  out$phi=object$phi.h0[,1]
  }
  return(out)
} 
